<?php

$this->title = "My Albums";
$this->headTitle($this->title);
?>
<p>
	<a
		href="<?php echo $this->url(array('controller'=>'index',
'action'=>'add'));?>">Add new album</a>
</p>
<?php if (count($this->paginator)): ?>
    <table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
          <?php foreach($this->paginator as $album): ?>

    <tr>
	      <td><?php echo $album->artist;?></td>
          <td><?php echo $album->title;?></td>
          <td><?php echo $album->date;?></td>
         <td><a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'delete', 'id'=>$album->id));?>">Delete</a></td> 
          
                  
    </tr>
    

    <?php endforeach; ?>
</table>
<?php endif; ?>
   <?php echo $this->paginationControl($this->paginator,
    'Sliding','index/pagination.phtml'); ?>
    
     <?php 
     $date = Zend_Date::now('pl_PL');
     #$date->get('YYYY-MM-dd HH:mm:ss');
     echo $date;
     ?>
